spring:
  application:
    name: GATEWAY-API

server:
  port: 6565

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

zuul:
  ignored-services: '*'
  prefix: /api
  routes:
    account-service:
      path: /account/**
      serviceId: ACCOUNT-SERVICE
    customer-service:
      path: /customer/**
      serviceId: CUSTOMER-SERVICE
  host:
    socket-timeout-millis: 30000

